services:
    products:
        build: ./products/docker/php-fpm
        container_name: products
        restart: unless-stopped
        working_dir: /var/www/products/site
        volumes:
            - ./products/docker/php-fpm/php.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
            - ./products/docker/php-fpm/php-fpm.conf:/etc/php/8.3/fpm/pool.d/z-overrides.conf
            - ./products/docker/php-fpm/log:/var/log/php-fpm
            - ./products:/var/www/products/site
        depends_on:
          - mysql
        networks:
            - common

    products_nginx:
      image: nginx:1.29.1-alpine
      container_name: products_nginx
      volumes:
        - ./products:/var/www/products/site
        - ./products/docker/nginx/conf.d:/etc/nginx/conf.d
        - ./products/docker/nginx/log:/var/log/nginx
      networks:
        - common
      ports:
        - "8001:80"
      depends_on:
        - products

    users:
      build: ./users/docker/php-fpm
      container_name: users
      restart: unless-stopped
      working_dir: /var/www/users/site
      volumes:
        - ./users/docker/php-fpm/php.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
        - ./users/docker/php-fpm/php-fpm.conf:/etc/php/8.3/fpm/pool.d/z-overrides.conf
        - ./users/docker/php-fpm/log:/var/log/php-fpm
        - ./users:/var/www/users/site
      depends_on:
        - mysql
      networks:
        - common

    users_nginx:
      image: nginx:1.29.1-alpine
      container_name: users_nginx
      volumes:
        - ./users:/var/www/users/site
        - ./users/docker/nginx/conf.d:/etc/nginx/conf.d
        - ./users/docker/nginx/log:/var/log/nginx
      networks:
        - common
      ports:
        - "8002:80"
      depends_on:
        - users

    notifications:
      build: ./notifications/docker/php-fpm
      container_name: notifications
      restart: unless-stopped
      working_dir: /var/www/notifications/site
      volumes:
        - ./notifications/docker/php-fpm/php.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
        - ./notifications/docker/php-fpm/php-fpm.conf:/etc/php/8.3/fpm/pool.d/z-overrides.conf
        - ./notifications/docker/php-fpm/log:/var/log/php-fpm
        - ./notifications:/var/www/notifications/site
      depends_on:
        - mysql
      networks:
        - common

    notifications_nginx:
      image: nginx:1.29.1-alpine
      container_name: notifications_nginx
      volumes:
        - ./notifications:/var/www/notifications/site
        - ./notifications/docker/nginx/conf.d:/etc/nginx/conf.d
        - ./notifications/docker/nginx/log:/var/log/nginx
      networks:
        - common
      ports:
        - "8003:80"
      depends_on:
        - notifications

    mysql:
      image: mysql:8
      container_name: mysql
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: password
      volumes:
        - ./mysql/my.cnf:/etc/mysql/conf.d/99-overrides.cnf
        - ./mysql/db:/var/lib/mysql
        - ./mysql/bak/:/bak
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "3306:3306"
      networks:
        - common

    mailpit:
      image: axllent/mailpit:v1.27
      container_name: mailpit
      ports:
        - "8025:8025"
        - "1025:1025"
      networks:
        - common

    rabbitmq:
      image: rabbitmq:4.1.4-management
      container_name: rabbitmq
      restart: unless-stopped
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
      volumes:
        - ./rabbitmq:/var/lib/rabbitmq
      ports:
        - "15672:15672"
        - "5672:5672"
      networks:
        - common

networks:
    common:
        external: true